### ISSUE TITLE
Exception running application due to wrong version of HtmlAgilityPack

### ISSUE THREAD

**Issue by mortenn** [lukeschafer/HtmlCleanser#6]
After installing HtmlCleanser to a clean project, if I do not update HtmlAgilityPack to 1.4.9, I get a runtime exception about not being able to load HtmlAgilityPack 1.4.9.
The installed version is 1.4.6

**Comment by lukeschafer** [comment]
My apologies, due to 'life', many emails over the last year have been burried in a 3000-strong unread email list that I've only just now gotten through. I will look at these issues if/when I have time shortly. In the meantime, I absolutely accept pull requests and would love any aid in getting this up to shape.

**Comment by atp-tha** [comment]
My PR here #10 would enable using this package with HtmlAgilityPack 1.4.9. Waiting for @lukeschafer to check the PR out.

**Comment by lukeschafer** [comment]
Fixed by PR #10
