### ISSUE TITLE
Failed to install nuget package on .net 4 and 4.5

### ISSUE THREAD

**Issue by arisliang** [lukeschafer/HtmlCleanser#9]
What version of .net this supports?

Detailed error:
Could not install package 'HtmlCleanser 1.0.6165.39272'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Similar error was on .net 4 that I tried.

**Comment by lukeschafer** [comment]
My apologies, due to 'life', many emails over the last year have been burried in a 3000-strong unread email list that I've only just now gotten through. I will look at these issues if/when I have time shortly. In the meantime, I absolutely accept pull requests and would love any aid in getting this up to shape.

**Comment by atp-tha** [comment]
My PR here #10 would enable using this package in net45. Waiting for @lukeschafer to check the PR out.

**Comment by lukeschafer** [comment]
PR #10 solved
